name: Deploy
on:
  # every day
  # schedule: 
    # - cron: '0 0 * * *'
  # or on push
  push:
    branches:
    - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: covid19-270622
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy app.yaml --no-promote
